name: build
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
      - run: npm ci
      - run: npm run tauri build
